language: android

dist: trusty

jdk:
  - oraclejdk8

before_install:
  # Install SDK licenses so Android Gradle plugin can install dependencies
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Decrypt publish required credentials.
  - openssl aes-256-cbc -K $encrypted_3c47f12a66a7_key -iv $encrypted_3c47f12a66a7_iv -in publish.properties.enc -out publish.properties -d
  - openssl aes-256-cbc -K $encrypted_3c47f12a66a7_key -iv $encrypted_3c47f12a66a7_iv -in publish_keys.gpg.enc -out publish_keys.gpg -d

script:
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      ./gradlew assembleRelease --stacktrace;
      exit $?;
    fi

  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
      if [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        ./gradlew assembleRelease uploadArchives --stacktrace;
        ./gradlew closeAndReleaseRepository --stacktrace;
        exit $?;
      fi
    fi

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
